import { motion } from 'framer-motion'

import { AppWrap } from '@/wrapper'
import { images } from '@/constants'
import './Header.scss'

/**
 * Served from `public/` rather than imported, so `index.html` can preload a URL
 * that is known before the build assigns content hashes. Generated by
 * `npm run images`.
 */
const HERO = '/hero'

/** Matches the widths the photo is actually laid out at, so the browser can
 *  pick a source before any CSS or JS has run. */
const HERO_SIZES = '(max-width: 900px) 60vw, 500px'

const scaleVariants = {
  whileInView: {
    scale: [0, 1] as [number, number],
    opacity: [0, 1] as [number, number],
    transition: { duration: 1, ease: 'easeInOut' as const },
  },
}

const Header = () => (
  <div className='app__header app__flex'>
    <motion.div
      whileInView={{ x: [-100, 0], opacity: [0, 1] }}
      transition={{ duration: 0.5 }}
      className='app__header-info'
    >
      <div className='app__header-badge'>
        <div className='badge-cmp app__flex'>
          <span role='img' aria-label='waving hand'>
            👋🏻
          </span>
          <div style={{ marginLeft: 20 }}>
            <p className='p-text'>Hello, I am</p>
            <h1 className='head-text'>Miguel</h1>
          </div>
        </div>

        <div className='tag-cmp app__flex'>
          <p className='p-text'>Software Engineer</p>
          <p className='p-text'>Entrepreneur</p>
        </div>
      </div>
    </motion.div>

    {/*
      Deliberately not a motion.div. This subtree holds the Largest Contentful
      Paint element, and fading it in from opacity 0 meant the photo could not
      paint until React had booted and the animation had run - 3.5s of the 8.1s
      mobile LCP was spent waiting on that, after the bytes had already arrived.
      The decorative circle behind it still animates; the photo itself does not.
    */}
    <div className='app__header-img'>
      <picture>
        <source
          type='image/avif'
          srcSet={`${HERO}/profile-400.avif 400w, ${HERO}/profile-617.avif 617w`}
          sizes={HERO_SIZES}
        />
        <source
          type='image/webp'
          srcSet={`${HERO}/profile-400.webp 400w, ${HERO}/profile-617.webp 617w`}
          sizes={HERO_SIZES}
        />
        <img
          src={`${HERO}/profile-617.png`}
          alt='Miguel Vilhena'
          width={617}
          height={911}
          // React 18 does not recognise the camelCase `fetchPriority` prop and
          // drops it silently, so the priority hint never reached the DOM. The
          // lowercase attribute passes straight through. React 19 supports the
          // camelCase form natively, so this can be simplified on upgrade.
          {...({ fetchpriority: 'high' } as Record<string, string>)}
          decoding='async'
        />
      </picture>
      <motion.img
        whileInView={{ scale: [0, 1] }}
        transition={{ duration: 1, ease: 'easeInOut' }}
        src={images.circle}
        alt=''
        aria-hidden='true'
        className='overlay_circle'
      />
    </div>

    <motion.div
      variants={scaleVariants}
      whileInView={scaleVariants.whileInView}
      className='app__header-circles'
    >
      {[images.react, images.typescript, images.node].map((circle, index) => (
        <div className='circle-cmp app__flex' key={`circle-${index}`}>
          <img src={circle} alt='' aria-hidden='true' loading='lazy' decoding='async' />
        </div>
      ))}
    </motion.div>
  </div>
)

export default AppWrap(Header, 'home')
