import type { Config } from '@netlify/functions'
import { createClient } from '@sanity/client'

/**
 * Redirects miguelvilhena.com/cv to whichever CV is currently set in Sanity, so
 * the public link never changes even when the underlying file does.
 *
 * Resolved server-side on each request rather than baked into the bundle, so
 * updating the CV needs no redeploy.
 *
 * The CV is now generated by `npm run cv` and served from this same site at
 * /cv.pdf, which is what Sanity points at. It lived in Google Drive before that
 * and may again, so both are accepted.
 */

/** The site's own origin, and the path the generated CV is published to. */
const SITE_URL = () => process.env.SITE_URL || 'https://miguelvilhena.com'

const FALLBACK_CV = () => `${SITE_URL()}/cv.pdf`

/**
 * Whether a CMS-supplied URL may be redirected to.
 *
 * Origin equality over string matching, and https only, so neither a stray
 * lookalike domain nor a downgraded scheme can pass.
 */
const isAllowed = (value: string): boolean => {
  let url: URL
  try {
    url = new URL(value)
  } catch {
    return false
  }

  if (url.protocol !== 'https:') return false

  return (
    url.origin === new URL(SITE_URL()).origin ||
    url.hostname === 'drive.google.com' ||
    url.hostname === 'docs.google.com'
  )
}

const sanity = createClient({
  projectId: process.env.SANITY_PROJECT_ID || process.env.VITE_SANITY_PROJECT_ID || 'khsof0do',
  dataset: process.env.SANITY_DATASET || 'production',
  apiVersion: '2024-01-01',
  useCdn: true,
})

export default async (req: Request) => {
  let target = FALLBACK_CV()
  let enabled = true

  try {
    const settings = await sanity.fetch<{ cvUrl?: string; cvEnabled?: boolean } | null>(
      '*[_id == "siteSettings"][0]{ cvUrl, cvEnabled }',
    )
    if (settings?.cvEnabled === false) enabled = false
    if (settings?.cvUrl) target = settings.cvUrl
  } catch (error) {
    // A Sanity outage should still serve the last known good link rather than
    // turning a CV people are actively opening into an error page.
    console.error('[cv] settings lookup failed, using fallback', error)
  }

  if (!enabled) {
    return new Response('CV is not currently available.', {
      status: 404,
      headers: { 'content-type': 'text/plain' },
    })
  }

  // An allowlist, not a sanity check: `target` comes from the CMS, so without
  // one a bad value here turns this route into an open redirect. Google Drive
  // and Docs are allowed because that is where the CV used to live, and this
  // site's own origin because that is where it lives now. Anything else is
  // refused and the request falls back rather than failing.
  //
  // Compared by parsed origin rather than by matching the string, because a
  // pattern built from a URL treats its dots as wildcards, and an allowlist
  // that accepts miguelvilhenaXcom is not an allowlist.
  //
  // The site's own origin was missing until 2026-08-17, which broke this route
  // silently: Sanity was pointing at /cv.pdf, the guard rejected it, and every
  // visitor to /cv was sent to the superseded Drive file instead. The route
  // returned 302 throughout, so nothing looked wrong.
  if (!isAllowed(target)) {
    console.error('[cv] refusing to redirect to an unexpected host', target)
    target = FALLBACK_CV()
  }

  // Drive needs a different endpoint to stream a file rather than preview it.
  // A self-hosted PDF has no such split, so this leaves it untouched: the regex
  // only matches Drive's /d/<id> path shape.
  const wantsDownload = new URL(req.url).searchParams.has('download')
  const fileId = /drive\.google\.com\/.*\/d\/([a-zA-Z0-9_-]+)/.exec(target)?.[1]

  const location =
    wantsDownload && fileId ? `https://drive.google.com/uc?export=download&id=${fileId}` : target

  return new Response(null, {
    status: 302,
    headers: {
      location,
      // Short cache: long enough to absorb bursts, short enough that a new CV
      // goes live within minutes rather than being pinned at the edge.
      'cache-control': 'public, max-age=300',
    },
  })
}

export const config: Config = {
  path: '/cv',
}
